# Generated by Django 4.1.3 on 2022-12-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ardipucp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(default="", max_length=64)),
                ("producto", models.CharField(default="", max_length=100)),
                ("imagen", models.CharField(default="", max_length=64)),
                ("precio", models.CharField(default="", max_length=64)),
                ("stock", models.CharField(default="", max_length=64)),
                ("descripcion", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
