# Generated by Django 4.1.3 on 2022-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ardipucp", "0002_productos"),
    ]

    operations = [
        migrations.CreateModel(
            name="promociones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(default="", max_length=64)),
                ("nombre", models.CharField(default="", max_length=100)),
                ("tipo", models.CharField(default="", max_length=64)),
                ("condición", models.CharField(default="", max_length=64)),
                ("precio", models.CharField(default="", max_length=64)),
                ("duración", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
